region            = "eu-west-1"
env               = "dev"
bucket_name       = "terraform-infraascode-bucket"
helm_release_name = "app-dev"
helm_chart_path   = "../helm"
helm_values_path  = "../helm/values.yaml"
