import random
from locust import HttpUser, task, between

class TaskUser(HttpUser):
    # Simulate a user waiting 0.5 to 2 seconds between actions
    wait_time = between(0.5, 2)
    
    # Store IDs created by this user to perform operations on them later
    task_ids = []

    def on_start(self):
        """Initialize the task list for each user when they start spawning"""
        self.task_ids = []

    @task(1)
    def view_root(self):
        """Check health/root"""
        self.client.get("/", name="Root Endpoint", verify=False)

    @task(3)
    def create_task(self):
        """Create a task and save its ID"""
        response = self.client.post("/tasks", json={
            "title": f"Load Test Task {random.randint(1, 10000)}",
            "description": "Generated by Locust"
        }, name="Create Task", verify=False)
        
        if response.status_code == 201:
            try:
                task_data = response.json()
                self.task_ids.append(task_data["id"])
            except Exception:
                pass

    @task(2)
    def list_tasks(self):
        """List all tasks"""
        self.client.get("/tasks", name="List Tasks", verify=False)

    @task(4)
    def get_task(self):
        """Get a specific task by ID"""
        if not self.task_ids:
            return

        task_id = random.choice(self.task_ids)
        with self.client.get(f"/tasks/{task_id}", name="Get Task", catch_response=True, verify=False) as response:
            if response.status_code == 404:
                # If it disappeared (deleted by another process?), remove it locally
                if task_id in self.task_ids:
                    self.task_ids.remove(task_id)
                response.success() # Mark as success or failure depending on strictness

    @task(2)
    def update_task(self):
        """Update a specific task (PUT)"""
        if not self.task_ids:
            return

        task_id = random.choice(self.task_ids)
        self.client.put(f"/tasks/{task_id}", json={
            "title": f"Updated Task {random.randint(1, 10000)}",
            "description": "Updated description by Locust"
        }, name="Update Task", verify=False)

    @task(2)
    def toggle_complete(self):
        """Toggle task status (PATCH)"""
        if not self.task_ids:
            return

        task_id = random.choice(self.task_ids)
        self.client.patch(f"/tasks/{task_id}/complete", name="Toggle Complete", verify=False)

    @task(1)
    def delete_task(self):
        """Delete a task and remove ID from local list (DELETE)"""
        if not self.task_ids:
            return

        task_id = random.choice(self.task_ids)
        with self.client.delete(f"/tasks/{task_id}", name="Delete Task", catch_response=True, verify=False) as response:
            if response.status_code == 204 or response.status_code == 404:
                if task_id in self.task_ids:
                    self.task_ids.remove(task_id)