receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  memory_limiter:
    limit_mib: 400
    spike_limit_mib: 100
    check_interval: "5s"

exporters:
  prometheusremotewrite:
    endpoint: "${amp_endpoint}api/v1/remote_write"

  debug:
      verbosity: detailed

  awsxray:
    region: "${region}"

  awscloudwatchlogs:
    log_group_name: "/aws/eks/adot-logs"
    log_stream_name: "collector"
    region: "${region}"

service:
  pipelines:
    metrics:
      receivers: ["otlp"]
      processors: ["memory_limiter", "batch"]
      exporters: ["prometheusremotewrite"]
    traces:
      receivers: ["otlp"]
      processors: ["memory_limiter", "batch"]
      exporters: ["awsxray", "debug"]
    logs:
      receivers: ["otlp"]
      processors: ["memory_limiter", "batch"]
      exporters: ["awscloudwatchlogs", "debug"]