replicaCount: 2

image:
  repository: REPLACE_WITH_ECR_URL
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

loadBalancer:
  name : task-manager
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: DATABASE_URL
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://adot-collector.observability.svc.cluster.local:4317"
  - name: OTEL_PYTHON_LOG_CORRELATION
    value: "true"
  - name: OTEL_SERVICE_NAME
    value: "true"

serviceAccount:
  create: true
  annotations: {}
  name: "app-sa"

ingress:
  enabled: false
  hosts: []
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  path: /health
  port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  path: /ready
  port: 8000
  initialDelaySeconds: 30
  periodSeconds: 5