replicaCount: 2

image:
  repository: REPLACE_WITH_ECR_URL
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

loadBalancer:
  name : task-manager
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations: {}

env:
  - name: DATABASE_URL
    value: "postgresql://..."
  # - name: API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: api-secrets
  #       key: api-key

ingress:
  enabled: false
  hosts: []
  tls: []

resources: {}

livenessProbe:
  path: /health
  port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /ready
  port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5